### ISSUE TITLE
Resilience4J metrics is not adding in to prometheus metric

### ISSUE THREAD

**Issue by nbenjamin** [resilience4j/resilience4j-spring-boot2-demo#27]
@RobWin Tried the following example, the only difference in the docker-compose configuration 

```yaml
    ports:
      - 9090:9090
    #network_mode: "host"
```

I see the resilience4J metric in actuator/metrics, however, I could not find in prometheus. Could you please let me know what is missing.

<img width="489" alt="Screen Shot 2020-01-13 at 5 43 01 AM" src="https://user-images.githubusercontent.com/870715/72249640-c3534600-35c7-11ea-9e47-f3d738c02933.png">

Here is what I see in Prometheus metrics

<img width="531" alt="Screen Shot 2020-01-13 at 5 45 18 AM" src="https://user-images.githubusercontent.com/870715/72249721-f39ae480-35c7-11ea-901d-aa00ae2c7538.png">

**Comment by RobWin** [comment]
Hi,
could you please provide some more context.
I assum you are using Spring Boot 2?
Did you add the library `io.micrometer:micrometer-registry-prometheus`.

The endpoint is usually ` http://localhost:9000/actuator/prometheus`

**Comment by nbenjamin** [comment]
I am using the provided [resilience4j-spring-boot2-demo](https://github.com/resilience4j/resilience4j-spring-boot2-demo) example in this repo.

Yes, dependency has `io.micrometer:micrometer-registry-prometheus.`
<img width="712" alt="Screen Shot 2020-01-13 at 7 36 52 AM" src="https://user-images.githubusercontent.com/870715/72256588-8f801c80-35d7-11ea-899a-596641077bb7.png">

spring actuator endpoint shows resilience4J metrics 

![Screen Shot 2020-01-13 at 7 36 17 AM](https://user-images.githubusercontent.com/870715/72256740-ea197880-35d7-11ea-97fe-ef8ada5960ba.png)

however, as I mentioned above its Prometheus
not displaying resilience4J metric options in the dropdown. 
***insert metric at cursor***
![Screen Shot 2020-01-13 at 7 39 32 AM](https://user-images.githubusercontent.com/870715/72256763-f9002b00-35d7-11ea-956b-6829f3e9b6de.png)

**Comment by RobWin** [comment]
Oh yes, I didn't notice that it was the demo repository ;) 

Can you find any other metrics from the application? Maybe prometheus cannot scrape your local application.

**Comment by nbenjamin** [comment]
yes, I can find other default metrics.
<img width="531" alt="Screen Shot 2020-01-13 at 5 45 18 AM" src="https://user-images.githubusercontent.com/870715/72260963-ea1e7600-35e1-11ea-9295-415402339389.png">

**Comment by RobWin** [comment]
The metrics are from prometheus itself. There are two scrapers. One for prometheus itself and one for the application which runs in a different container. It might be that the container-to-cotainer network doesn't work in your set-up?

**Comment by nbenjamin** [comment]
Yeah looks like, here is the updated docker-compose for mac
```yaml
version: '3'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    #network_mode: "host"
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    #network_mode: "host"
    env_file:
      - ./docker/grafana.env
```


I tried adding network bridge as well, however, did not work

**Comment by nbenjamin** [comment]
I dont see any issue with container-container communication, for example i can see both here
<img width="613" alt="Screen Shot 2020-01-13 at 10 31 01 AM" src="https://user-images.githubusercontent.com/870715/72268511-ef82bd00-35ef-11ea-8d82-96d15c02ba6e.png">

But still not resilience4J metric

**Comment by RobWin** [comment]
That's just the internal configuration

**Comment by artemzi** [comment]
Same here, I use docker-compose config from example project and successfully connect the first project, then added second `job_name` into `prometheus.yml` with identical config but there is no Prometheus endpoints in actuator and i got `"INVALID" is not a valid start token` in Prometheus targets.

**Comment by artemzi** [comment]
@nbenjamin try to add this in you config
```
management:
  endpoints:
    web:
      exposure:
        include: '*'
  server:
    servlet:
      context-path: /actuator
```
