### ISSUE TITLE
CircuitBreaker with Retry

### ISSUE THREAD

**Issue by MMaalej** [resilience4j/resilience4j-spring-boot2-demo#29]
Hi,

I want to define a Cuircuit-Breaker with retry for a restcall.
My Config:

```
resilience4j.circuitbreaker:
    configs:
        default:
            registerHealthIndicator: false
            slidingWindowSize: 10
            minimumNumberOfCalls: 2
            permittedNumberOfCallsInHalfOpenState: 3
            automaticTransitionFromOpenToHalfOpenEnabled: true
            waitDurationInOpenState: 10s
            slowCallDurationThreshold: 10
            slowCallRateThreshold: 30
    instances:
        restCallCB:
            baseConfig: default
            
resilience4j.retry:
    configs:
        default:
            maxRetryAttempts: 2
            waitDuration: 1000
    instances:
        restCallRE:
            baseConfig: default
```

I use this spring annotation:

```
@CircuitBreaker(name = "restCallCB")
@Retry(name = "restCallRE", fallbackMethod = "fallbackRetry")
public String callRest(...)
```

I use a wrong URL to test the restcall.
Problem: the retry will not be executed und the circuit breaker ist alway closed.

If I define a fallback-Method for the circuit breaker, the first test call this fallback-Method and the retry will not be executed. Without the circuit breaker the retry works fine.

Could you please help me find the right config.

Thanks,
Maalej
