### ISSUE TITLE
TimeLimiter Configuration wrong in application.yml

### ISSUE THREAD

**Issue by fstorz** [resilience4j/resilience4j-spring-boot2-demo#32]
In the file `src/main/resources/application.yml`, the following timelimiter configuration is present

```
resilience4j:
    configs:
        default:
            cancelRunningFuture: false
            timeoutDuration: 2s
```

This config should be 

```
resilience4j.timelimiter:
    configs:
        default:
            cancelRunningFuture: false
            timeoutDuration: 2s
```
