### ISSUE TITLE
Description of the options found in YML properties as documentation

### ISSUE THREAD

**Issue by patpatpat123** [resilience4j/resilience4j-spring-boot2-demo#46]
Hello Resilience4j,

First of all, a big thanks for this demo project.
Having the ability to just run and see resilience4j in action really helps build confidence and interest in this the whole fault-tolerant architecture.

I just have a small request for enhancement, if possible, and hope not to trouble.
Would it be possible to have a documentation listing the options and configurations please?

Currently, in the doc, we can find something such as:

```
resilience4j.circuitbreaker:
    instances:
        backendA:
            registerHealthIndicator: true
            slidingWindowSize: 100
        backendB:
            registerHealthIndicator: true
            slidingWindowSize: 10
            permittedNumberOfCallsInHalfOpenState: 3
            slidingWindowType: TIME_BASED
            minimumNumberOfCalls: 20
            waitDurationInOpenState: 50s
            failureRateThreshold: 50
            eventConsumerBufferSize: 10
            recordFailurePredicate: io.github.robwin.exception.RecordFailurePredicate

```

Agree, some of the properties/configurations are very straightforward.
However, some are not, and having to tune the values on trial and error might not be the best approach.

Some documentation pages, like those found in other Spring Boot projects can help understand this in a friendly way.
Some human readable explanations can definitely bring more values.

Many thanks
